### ISSUE TITLE
Conflict with Gravity Forms 2.5.3

### ISSUE THREAD

**Issue by bhubbard** [bugsnag/bugsnag-wordpress#58] opened 2021-06-22 20:08 UTC
### Describe the bug
Install/Activate Gravity Forms 2.5.3 or higher, site will slow down and bugsnag will just start filling with lots of errors, such as the example below: 

```PHP Warning · DOMDocument::loadXML(): xmlParseEntityRef: no name in Entity, line: 838```

https://screenshots.brandonhubbard.com/9ZudRlN6
https://screenshots.brandonhubbard.com/lluNkRYK

### Environment
* Bugsnag version:  1.6.0 
* PHP version: 7.4
* Wordpress version: 5.7.2
* Gravity Forms version: 2.5.6

**Comment by johnkiely1** [comment] 2021-06-23 10:39
Hi @bhubbard. 

Based on your second screenshot it looks like the problem is occurring due to there being more than 256 events in a single payload being sent to Bugsnag at once. 

https://github.com/bugsnag/bugsnag-php/blob/2.10/src/Bugsnag/Notification.php#L140-L157 is the code in question. Each iteration removes an event so there must be more than 256 events in that payload to hit that limit. It would seem that whatever problem Gravity forms is encountering it is generating hundreds of warnings which is presumably what is causing the slowdown. Have you been able to determine the underlying cause of the error? 

If you know that is an error/warning you can safely ignore you could also implementing the following
https://docs.bugsnag.com/platforms/php/wordpress/customizing-error-reports/#before-notify-callbacks
and preventing errors with that message from being sent to Bugsnag.

**Comment by mattdyoung** [comment] 2021-07-07 11:20
Closing as we don't believe this is an issue with Bugsnag, it's just reporting the very high volume of warnings/errors being output.

**Closed by mattdyoung** 2021-07-07 11:20 UTC
