### ISSUE TITLE
Possible compatibility issues with PHP 7

### ISSUE THREAD

**Issue by CodeHex** [bugsnag/bugsnag-wordpress#15] opened 2016-08-30 10:24 UTC
This exception occurred when sending errors using the wordpress package using PHP7

```
Fatal error: Uncaught TypeError: Argument 3 passed to Bugsnag_Error::fromPHPException() must be an instance of Exception, instance of Error given, called in
/home/vagrant/Sites/example.com/public/app/plugins/bugsnag/bugsnag-php/Client.php on line 360 and defined in 
/home/vagrant/Sites/example.com/public/app/plugins/bugsnag/bugsnag-php/Error.php:31 

Stack trace: 
#0 /home/vagrant/Sites/example.com/public/app/plugins/bugsnag/bugsnag-php/Client.php(360): Bugsnag_Error::fromPHPException(Object(Bugsnag_Configuration), Object(Bugsnag_Diagnostics), Object(Error)) 
#1 [internal function]: Bugsnag_Client->exceptionHandler(Object(Error)) 
#2 {main} thrown in /home/vagrant/Sites/example.com/public/app/plugins/bugsnag/bugsnag-php/Error.php on line 31
```

**Comment by GrahamCampbell** [comment] 2016-08-30 14:19
Yeh, we just need to download the newest v2 from the PHP library and put it in here.

**Comment by GrahamCampbell** [comment] 2016-08-30 14:19
Wait, but actually, I already fixed this? https://github.com/bugsnag/bugsnag-wordpress/commit/b704bdb9be1df26c382def3618e7cd0c1d5ab93e

**Comment by GrahamCampbell** [comment] 2016-08-30 14:20
Guess we just need to release 1.3.0?

**Comment by GrahamCampbell** [comment] 2016-08-30 14:21
https://github.com/bugsnag/bugsnag-wordpress/pull/16

**Comment by GrahamCampbell** [comment] 2016-08-30 14:21
Not sure what else we need to do regarding actually publishing this for use?

**Comment by mikebronner** [comment] 2016-09-04 00:39
I will give it a go using the `dev-master` to see if it works (I originally reported the issue a few days back) and let you know.

**Comment by mikebronner** [comment] 2016-09-12 23:31
I was able to reproduce the issue again:

```
Fatal error: Uncaught TypeError: Argument 3 passed to Bugsnag_Error::fromPHPException() must be an instance of Exception, instance of Error given, called in /home/vagrant/Sites/maureentaylor.com/public/app/plugins/bugsnag/bugsnag-php/Client.php on line 360 and defined in /home/vagrant/Sites/maureentaylor.com/public/app/plugins/bugsnag/bugsnag-php/Error.php:31 Stack trace: #0 /home/vagrant/Sites/maureentaylor.com/public/app/plugins/bugsnag/bugsnag-php/Client.php(360): Bugsnag_Error::fromPHPException(Object(Bugsnag_Configuration), Object(Bugsnag_Diagnostics), Object(Error)) #1 [internal function]: Bugsnag_Client->exceptionHandler(Object(Error)) #2 {main} thrown in /home/vagrant/Sites/maureentaylor.com/public/app/plugins/bugsnag/bugsnag-php/Error.php on line 31
```

Here's the code that caused it, where `$content` is a snippet of HTML:
```php
    $dom = new DOMDocument();
    $dom->loadHTML($content);

    $caption = $dom->documentElement();

    var_dump($caption); die();
```

**Comment by mikebronner** [comment] 2016-09-12 23:33
This is probably a duplicate of #13 and #14.

**Comment by tillkruss** [comment] 2016-10-07 18:21
I'm getting this error with v1.3.0:

```
Fatal error: Uncaught TypeError: Argument 3 passed to Bugsnag_Error::fromPHPException() must be an instance of Exception, instance of TypeError given, called in /app/web/app/plugins/bugsnag/bugsnag-php/Client.php on line 360 and defined in /app/web/app/plugins/bugsnag/bugsnag-php/Error.php:31
Stack trace:
#0 /app/web/app/plugins/bugsnag/bugsnag-php/Client.php(360): Bugsnag_Error::fromPHPException(Object(Bugsnag_Configuration), Object(Bugsnag_Diagnostics), Object(TypeError))
#1 [internal function]: Bugsnag_Client->exceptionHandler(Object(TypeError))
#2 {main}
  thrown in /app/web/app/plugins/bugsnag/bugsnag-php/Error.php on line 31

**Comment by kattrali** [comment] 2016-11-29 16:08
Fixed via 1.2.0/1.3.0.

**Closed by kattrali** 2016-11-29 16:08 UTC
